# Generated by Django 3.1.2 on 2020-12-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
