# Generated by Django 3.1 on 2020-09-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('details', models.TextField()),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=100)),
                ('maximum_signups', models.IntegerField(help_text='Set to something < 1 if signing up is not required')),
                ('signups_open_date', models.DateTimeField(blank=True, null=True)),
                ('signups_close_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-event_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
    ]
