# Generated by Django 3.1.14 on 2022-01-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200903_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
