# Generated by Django 3.1.14 on 2022-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_signup_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
