# Generated by Django 3.1 on 2020-08-30 18:25

from django.db import migrations, models
import django.db.models.deletion
import apps.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(blank=True, default=apps.members.models.get_random_nickname, max_length=30)),
                ('show_full_name', models.BooleanField(default=False)),
                ('avatar_image', models.ImageField(blank=True, null=True, storage=apps.members.models.OverwriteStorage(), upload_to=apps.members.models.avatar_image_path)),
                ('discord_tag', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
