# Generated by Django 6.0.7 on 2026-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='discord_tag',
            new_name='discord_username',
        ),
        migrations.AddField(
            model_name='member',
            name='discord_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
