# Generated by Django 3.1.14 on 2023-01-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211206_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
