# Generated by Django 3.1 on 2020-09-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='last_shown_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_showing', to='showings.show'),
        ),
    ]
