# Generated by Django 3.1.12 on 2021-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0003_auto_20200903_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='title_english',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_romaji',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
