# Generated by Django 3.1 on 2020-09-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(choices=[(1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Academic year starting in')),
                ('history', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Academic Year Entries',
            },
        ),
        migrations.CreateModel(
            name='ExecEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_name', models.CharField(max_length=30)),
                ('exec_role', models.CharField(max_length=30)),
                ('related_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.academicyearentry')),
            ],
        ),
    ]
