# Generated by Django 3.1 on 2020-09-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Displayed name rather than filename.', max_length=40, null=True)),
                ('type', models.CharField(choices=[('im', 'Image'), ('vi', 'Video')], default='im', max_length=2)),
                ('date', models.DateField(help_text='Date of creation or last known time.')),
                ('file', models.FileField(help_text='The file that should be uploaded', upload_to='archive/')),
                ('details', models.TextField(blank=True, help_text='Any details about the item', null=True)),
            ],
        ),
    ]
