# Generated by Django 3.1.12 on 2021-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='anilist_url',
            field=models.URLField(blank=True),
        ),
    ]
