# Generated by Django 3.1.14 on 2023-05-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('karaoke', '0002_auto_20210927_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member'),
        ),
    ]
