# Generated by Django 3.1 on 2020-09-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_populate_data', models.BooleanField(default=False, help_text='Check this to use AniList to populate fields.')),
                ('title_romaji', models.CharField(blank=True, max_length=110)),
                ('title_english', models.CharField(blank=True, max_length=110)),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('series_type', models.CharField(blank=True, max_length=10)),
                ('synopsis', models.TextField(blank=True)),
                ('cover_link', models.URLField(blank=True)),
                ('anilist_link', models.URLField(blank=True)),
                ('mal_link', models.URLField(blank=True)),
                ('cooldown_end_date', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('showing_type', models.CharField(choices=[('wk', 'Weekly showing'), ('an', 'All-nighter'), ('mo', 'Movie Night'), ('ot', 'Other')], default='wk', max_length=2)),
                ('showing_title', models.CharField(blank=True, help_text='You only need to set this if the event has a unique name.', max_length=50, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(help_text='Episodes watched (Ep.1, Eps. 1-3), ect.', max_length=200)),
                ('show_type', models.CharField(choices=[('ms', 'Main series'), ('mc', 'Main series candidate'), ('ex', 'Exec choice'), ('mv', 'Movie Night'), ('an', 'All-nighter'), ('ot', 'Other')], max_length=2)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showings.series')),
                ('shown_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showings.showing')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='last_shown_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_showing', to='showings.show'),
        ),
    ]
